[project]
name = "big-pptx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "natsort>=8.4.0",
    "python-pptx>=1.0.2",
    "python-slugify>=8.0.4",
    "scipy>=1.14.1",
]
